#!/bin/bash
# Note that this script is only ever expected to be source-d into another
# script - the !/bin/bash comment above is just so that vim can do
# syntax-highlighting correctly.

export CW_RPM_UTILS_TOPDIR=$1
export CW_RPM_UTILS_BUILDROOT=$2

function setup_buildroot {
  rm -rf ${CW_RPM_UTILS_BUILDROOT}
  copy_to_buildroot build-infra/LICENSE
}

function copy_to_buildroot {
  mkdir -p ${CW_RPM_UTILS_BUILDROOT}$2
  cp -rp ${CW_RPM_UTILS_TOPDIR}/$1 ${CW_RPM_UTILS_BUILDROOT}/$2
}

function install_to_buildroot {
  export -f copy_to_buildroot
  xargs -r -I {} bash -c 'copy_to_buildroot "$(cut -d\  -f 1 <<< "{}")" "$(cut -d\  -f 2 <<< "{}")"'
}

function dirs_to_buildroot {
  xargs -r -I {} mkdir -p ${CW_RPM_UTILS_BUILDROOT}/{}
}

function build_files_list {
  { cd ${CW_RPM_UTILS_BUILDROOT}
    find . -type f -o -type d -empty
    cd - > /dev/null
  } |
  sed -e 's/^\.//g' |
  sed -e 's/^\/etc\//%config \/etc\//g' |
  egrep -v "^/LICENSE$"
  echo %doc /LICENSE
}
